name: IEA indicator catalog entry
description: Use this issue template to submit catalog information for GOM Wind IEA indicators.
title: "[Submission]: "
labels: ["submission"]
assignees: "CarissaGervasi-NOAA"
body:
  - type: markdown
    attributes:
      value: |
        Please reach out to Will (willem.klajbor@noaa.gov) with any questions or concerns.
  - type: input
    id: contact1
    attributes:
      label: Primary Contact
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@noaa.gov
    validations:
      required: true
  - type: dropdown
    id: indicator_name
    attributes:
      label: Indicator Name (from list of selected indicators)
      description: Select from the drop down
      options:
        - Sensitive Habitat Modification
        - Avian Distribution and Wellbeing
        - Trophic Impacts
        - Protected Species Distribution and Wellbeing
        - Reef Fish
        - Fish Recruitment
        - Other Faunal (Bat, Insect, etc.) Wellbeing
        - Benthic Modification
        - Sustainability / Maintenance of OSW Infrastructure 
        - Contaminants
        - EMF
        - Noise
        - Footprint/Hazards/Space Occupied in Water
        - Marine Recreational Activities (inc. Rec Fishing and Diving)
        - Media / Narratives
        - Perception of Ecosystem Health
        - Commercial Fishing 
        - Energy Security / Proportion of Energy Supplied by Clean Sources        
        - Fishing Opportunity and Accessibility
        - Sense of Place
        - Community / Water Dependent Population Economic Wellbeing
        - Trust in / Knowledge of OSW Development Process
        - Workforce Development
    validations:
      required: true
        
  - type: checkboxes
    id: indicator_category
    attributes:
      label: Category (Which group is this indicator associated with?)
      description: Please check the group(s) that could apply to your indicator.
      options:
        - label: Biological
        - label: Physical / Chemical
        - label: Human Dimensions
    validations:
      required: true
 
  - type: textarea
    id: data_description
    attributes:
      label: Data Description
      description: Briefly describe the data set(s) used for this indicator.
      value: "Ex: The data presented here are average annual sea-surface temperatures from PSL OISST on the Northeast Continental Shelf."
    validations:
      required: true
  - type: textarea
    id: indicator_intro
    attributes:
      label: Introduction to Indicator (Please explain your indicator)
      description: Please introduce the indicator within an appropriate context.
      value: "Proceed as though this were a short summary of a typical introduction section in a paper."
    validations:
      required: false
  - type: textarea
    id: indicator_results
    attributes:
      label: Key Results and Visualization
      description: Please describe the results and/or visualizations of this indicator.
      value: "Proceed as though this were a short summary of a typical results section in a paper."
    validations:
      required: false
  - type: textarea
    id: indicator_implications
    attributes:
      label: Implications
      description: Please describe the implications of this indicator.
      value: "Proceed as though this were a short summary of a typical discussion section in a paper."
    validations:
      required: false
  - type: input
    id: spatial_scale
    attributes:
      label: Spatial Scale
      description: Please briefly describe the spatial scale of the indicator.
      placeholder: ex. inshore Louisiana.
    validations:
      required: false
  - type: input
    id: temporal_scale
    attributes:
      label: Temporal Scale
      description: Please briefly describe the temporal scale of the indicator.
      placeholder: ex. Spring (January-June), Fall (July-December), Annual.
    validations:
      required: false      
  - type: textarea
    id: define_variables
    attributes:
      label: Define Variables
      description: Provide definitions for all variable names with units.
      value: "Ex: 1) Name: piscivore_biomass; Definition: Biomass of piscivores; Units: kg tow^-1. 2) Name: forage_biomass; Definition: Biomass of forage fish; Units: kg tow^-1."
    validations:
      required: true
  - type: textarea
    id: data_contributors
    attributes:
      label: Data Contributors
      description: Enter the names of all contributing persons.
      value: "Ex: Brandon Beltz, Sarah Gaichas and Sean Lucey."
    validations:
      required: true
  - type: input
    id: point_contact
    attributes:
      label: Point(s) of Contact
      description: Enter name(s) and email(s) for point(s) of contact.
      placeholder: Ex. Brandon Beltz (brandon.beltz@noaa.gov)
    validations:
      required: true
      
      
  - type: input
    id: affiliation
    attributes:
      label: Affiliation
      description: Enter the name of your affiliation.
      placeholder: Ex. NEFSC, GARFO, SMAST, MAFSC etc.
    validations:
      required: true
      
      
      
  - type: dropdown
    id: public_availability
    attributes:
      label: Public Availability
      description: State public availability of source data for this indicator.
      multiple: false
      options:
        - Source data are publicly available.
        - Source data are NOT publicly available.
    validations:
      required: true
  - type: input
    id: accessibility
    attributes:
      label: Accessibility and Constraints
      description: If source data are NOT publicly available, what are the procedures for accessing the data?
      placeholder: Ex. Please email your.email@noaa.gov for further information and queries of X indicator source data.
    validations:
      required: false
