name: Fall-Winter 2024 Use this: IEA-Wind Technical Document Entry
description: Use this issue template to submit information about indicators for the technical document for the Offshore Wind ESR.
title: "[Tech_Doc_Entry]: "
labels: ["Tech_Doc_Entry"]
assignees: []
body:
  - type: input
    id: submitter_name
    attributes:
      label: Submitter Name
      description: "Please provide your name here."
      placeholder: "Jane Doe"
      
  - type: input
    id: submitter_email
    attributes: 
      label: Submitter E-mail
      description: "Please provide your email below."
      placeholder: "youremail@noaa.gov"
      
  - type: input
    id: data_poc
    attributes:
        label: Data Provider POC
        description: "Please provide the name of the data provider (person or monitoring program)."
        placeholder: "Data Provider Name"

  - type: input
    id: sme_poc
    attributes: 
        label: Subject Matter Expert POC
        description: "Please recommend a subject matter expert in this data type."
        placeholder: "SME Name"
        
  - type: input
    id: sme_email
    attributes: 
        label: Subject Matter Expert E-mail
        description: "Please provide the email for the recommended SME."
        placeholder: "sme_email@noaa.gov"
        
  - type: checkboxes
    id: indicator_family
    attributes:
      label: Indicator Family
      description: "Which indicator family is this data associated with? Please check all that may apply."
      options:
        - label: Biological
        - label: Physical/Chemical
        - label: Human Dimensions

  - type: dropdown
    id: indicator_name
    attributes:
      label: "Please select the indicator name."
      options:
        - Avian Distribution and Wellbeing
        - Benthic Modification                                            
        - Commercial Fishing                                              
        - Community / Water Dependent Population Economic Wellbeing       
        - Contaminants                                                    
        - EMF                                                             
        - Energy Security / Proportion of Energy Supplied by Clean Sources
        - Fishing Opportunity and Accessibility                           
        - Footprint/Hazards/Space Occupied in Water                       
        - Marine Recreational Activities (inc. Rec Fishing and Diving)    
        - Media / Narratives                                              
        - Noise                                                           
        - Other Faunal (Bat, Insect, etc.) Wellbeing                      
        - Perception of Ecosystem Health                                  
        - Protected Species Distribution and Wellbeing                    
        - Reef Fish,Fish Recruitment                                      
        - Sense of Place                                                  
        - Sensitive Habitat Modification                                  
        - Sustainability / Maintenance of OSW Infrastructure              
        - Trophic Impacts                                                 
        - Trust in/ Knowledge of OSW Development Process                  
        - Workforce Development
        - Other

  - type: textarea
    id: found_in
    attributes:
      label: Found In
      description: "Where have other versions of this indicator been reported previously?"
      placeholder: "ex: 2015 Gulf of Mexico IEA ESR, link:"

  - type: dropdown
    id: public_availability
    attributes:
      label: Public Availability
      description: "State public availability of source data for this indicator."
      multiple: false
      options:
        - Source data are publicly available.
        - Source data are NOT publicly available.

  - type: input
    id: data_link
    attributes: 
      label: Data Link
      description: "Provide a Direct Link to the Data, if available."
      placeholder: "url"
      
  - type: input
    id: data_version
    attributes: 
      label: Data Version
      description: "Is there an associated verision identifier associated with this data source?"
      placeholder: "Version"
      
  - type: checkboxes
    id: manual_effort
    attributes:
      label: Manual Effort Required
      description: "How easily accessible is the data to access?"
      options:
        - label: API (Direct Download in correct format)
        - label: Medium (Download with some data modification, PDF scrape)
        - label: High (Indirect Access)

  - type: textarea
    id: data_resolution
    attributes:
      label: Data Resolution
      description: "Please provide a description of the spatial and temporal scale of the data source."
      placeholder: "temporal - 2008-present, annual. spatial - entire US Northern Gulf of Mexico"
      
  - type: textarea
    id: limitations_caveats
    attributes:
      label: Data Limitations & Caveats
      description: "Are there any known data limitations or caveats associated with this data source?"

  - type: textarea
    id: references
    attributes:
      label: References & Data Use Examples
      description: "Please link or attach any papers or references utilizing or explaining this data source."

  - type: textarea
    id: methods
    attributes:
      label: Methods
      description: "If known, please provide methods that will be used to process and analyze these data. This can be a code chunk or plain language description."

  - type: textarea
    id: other
    attributes:
      label: Other Comments
      description: "Please share any additional information about the data or your thoughts about this form here."
