project:
  type: website

website:
  title: "Wind IEA WIP Website"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: Indicator_Pg_Temp.qmd
        text: "Human Dimensions"
      - href: about.qmd
        text: "About"
        
    right:
      - text: "BLANKS"
        menu:
          - text: "page a"
          - text: "page b"
          - text: "page c"
    tools:
      - icon: github
        href: https://github.com/Gulf-IEA/Wind-ESR
        
format:
  html: 
    page-layout: full
    css:
      - css/wip_css.css
    include-after-body:
      file: html/footer.html
execute: 
  echo: false
  warning: false